spring.application.name=Warehouses

spring.datasource.url=jdbc:mysql://localhost:3306/Warehouse
spring.datasource.username=root
spring.datasource.password=tejesh@07

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

jwt.secret=gW1ZlxEj3oPBGmpoo30nEuQo92xdC2Ltl/e8tqomda4=
jwt.expiration=3600000